//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\Projects\Petroglyph\AloViewer 1.0\AloViewer.de.rc
//
#define IDD_SETTINGS                    103
#define IDR_MAINMENU                    104
#define IDR_ACCELERATOR1                110
#define IDD_CAMERA                      111
#define IDD_DETAILS                     113
#define IDD_DETAILS_PARAMETER           115
#define IDD_DETAILS_BONE                116
#define IDD_DETAILS_PROXY               117
#define IDD_DETAILS_MESH                118
#define IDD_DETAILS_LIST                119
#define IDD_DETAILS_VERTICES            119
#define IDD_DETAILS_FACES               120
#define IDD_DETAILS_LIGHT               121
#define IDD_SELECTION                   122
#define IDD_DIALOG1                     123
#define IDD_SELECT_SUBFILE              123
#define IDD_DETAILS_BONEMAPPING         124
#define IDR_SHADERLOD_MENU_EAW          126
#define IDR_SHADERLOD_MENU_EAW1         127
#define IDR_SHADERLOD_MENU_UAW_EA       127
#define IDD_ABOUT                       128
#define IDS_EXPAT_COPYRIGHT             129
#define IDD_DETAILS_DAZZLE              129
#define IDS_DISCLAIMER                  130
#define IDS_ERR_UNABLE_TO_OPEN_FILE     131
#define IDS_ERR_UNABLE_TO_OPEN_ANIMATION 132
#define IDS_ERR_UNABLE_TO_OPEN_MODEL    133
#define IDS_FILES_ALAMO                 134
#define IDS_FILES_ALL                   135
#define IDS_SELECTION_ANIMATIONS        136
#define IDS_SELECTION_BONES             137
#define IDS_SELECTION_MESHES            138
#define IDS_SELECTION_PROXIES           139
#define IDS_SELECTION_DAZZLES           140
#define IDS_INTERFACE_BACKGROUND        141
#define IDS_INTERFACE_COLORIZATION      142
#define IDS_CAMERA_NAME                 143
#define IDS_CAMERA_POSITION             144
#define IDS_CAMERA_TARGET               145
#define IDS_DETAILS_PARAMETER           146
#define IDS_DETAILS_VERTICES            147
#define IDS_DETAILS_FACES               148
#define IDS_DETAILS_BONE_MAPPING        149
#define IDS_DETAILS_MATERIAL            150
#define IDS_DETAILS_BONE                151
#define IDS_DETAILS_SKELETON            152
#define IDS_DETAILS_MESH                153
#define IDS_DETAILS_LIGHT               154
#define IDS_DETAILS_PROXY               155
#define IDS_DETAILS_DAZZLE              156
#define IDS_DETAILS_STRUCTURE           157
#define IDS_DETAILS_HIERARCHY           158
#define IDS_DETAILS_VERT_POSITION       159
#define IDS_DETAILS_VERT_NORMAL         160
#define IDS_DETAILS_VERT_TEXCOORDS      161
#define IDS_DETAILS_PARAM_FLOAT         162
#define IDS_DETAILS_PARAM_INTEGER       163
#define IDS_DETAILS_VERT_TANGENT        164
#define IDS_DETAILS_VERT_BINORMAL       165
#define IDS_DETAILS_VERT_COLOR          166
#define IDS_DETAILS_VERT_INDICES        167
#define IDS_DETAILS_VERT_WEIGHTS        168
#define IDS_DETAILS_MAPPING_BONE        169
#define IDS_DETAILS_MAPPING_NAME        170
#define IDS_DETAILS_FACES_VERT          171
#define IDS_DETAILS_PARAM_FLOAT3        172
#define IDS_DETAILS_PARAM_FLOAT4        173
#define IDS_YES                         174
#define IDS_NO                          175
#define IDS_DETAILS_LIGHT_OMNI          176
#define IDS_DETAILS_LIGHT_DIRECTIONAL   177
#define IDS_DETAILS_LIGHT_SPOT          178
#define IDS_STRING179                   179
#define IDS_DETAILS_PARAM_TEXTURE       179
#define IDS_NLOHMANNJSON_COPYRIGHT      180
#define IDC_EDIT1                       1002
#define IDC_SAVE                        1003
#define IDC_LOAD                        1004
#define IDC_DELETE                      1005
#define IDC_LIST1                       1006
#define IDC_TREE1                       1007
#define IDC_NAME                        1008
#define IDC_SPINNER1                    1009
#define IDC_CONTAINER                   1009
#define IDC_TYPE                        1009
#define IDC_SPINNER2                    1010
#define IDC_VALUE                       1010
#define IDC_SPINNER3                    1011
#define IDC_INDEX                       1011
#define IDC_SPINNER4                    1012
#define IDC_VISIBLE                     1012
#define IDC_SPINNER5                    1013
#define IDC_REL_TRANSFORM1              1013
#define IDC_SPINNER6                    1014
#define IDC_BONE                        1014
#define IDC_ABS_TRANSFORM1              1014
#define IDC_SPINNER7                    1015
#define IDC_ALTDECSTAYHIDDEN            1015
#define IDC_REL_TRANSFORM2              1015
#define IDC_SPINNER8                    1016
#define IDC_REL_TRANSFORM3              1016
#define IDC_TEXTURE                     1016
#define IDC_SPINNER9                    1017
#define IDC_BOUNDINGBOX                 1017
#define IDC_REL_TRANSFORM4              1017
#define IDC_ALTDECSTAYHIDDEN3           1017
#define IDC_SPINNER10                   1018
#define IDC_NAME2                       1018
#define IDC_PARENT                      1018
#define IDC_COLLIDABLE                  1018
#define IDC_FREQUENCY                   1018
#define IDC_TIMING                      1018
#define IDC_COLOR1                      1019
#define IDC_TAB1                        1019
#define IDC_ABS_TRANSFORM2              1019
#define IDC_PHASE                       1019
#define IDC_CHECK1                      1020
#define IDC_TAB2                        1020
#define IDC_ABS_TRANSFORM3              1020
#define IDC_BIAS                        1020
#define IDC_CHECK2                      1021
#define IDC_COLOR                       1021
#define IDC_ABS_TRANSFORM4              1021
#define IDC_CHECK3                      1022
#define IDC_INTENSITY                   1022
#define IDC_ALTDECSTAYHIDDEN8           1022
#define IDC_CHECK4                      1023
#define IDC_FARATTENTUATION             1023
#define IDC_FARATTENUATION              1023
#define IDC_COLOR2                      1024
#define IDC_COLOR3                      1025
#define IDC_COLOR4                      1026
#define IDC_HOTSPOTSIZE                 1026
#define IDC_COLOR5                      1027
#define IDC_FALLOFFSIZE                 1027
#define IDC_COLOR6                      1028
#define IDC_SELECT_ALT                  1028
#define IDC_SPINNER11                   1029
#define IDC_SELECT_LOD                  1029
#define IDC_CHECK5                      1030
#define IDC_SPIN1                       1030
#define IDC_TREE2                       1031
#define IDC_SPIN2                       1031
#define IDC_BUTTON1                     1031
#define IDC_LIST2                       1032
#define IDC_LIST3                       1033
#define IDC_BUTTON2                     1034
#define IDC_BUTTON_SHOW                 1034
#define IDC_BUTTON3                     1035
#define IDC_BUTTON_TOGGLE               1035
#define IDC_VERSION                     1035
#define IDC_BUTTON4                     1036
#define IDC_BUTTON_HIDE                 1036
#define IDC_BUILDDATE                   1036
#define IDC_LIST4                       1037
#define IDC_EXPAT_COPYRIGHT             1037
#define IDC_DISCLAIMER                  1038
#define IDC_POSITION                    1039
#define IDC_RADIUS                      1040
#define IDC_NIGHTONLY                   1041
#define IDC_SPINNER12                   1042
#define IDC_NLOHMANNJSON_COPYRIGHT      1043
#define ID_FILE_OPENMODEL               40001
#define ID_FILE_OPENANIMATION           40002
#define ID_FILE_EXIT                    40003
#define ID_FILE_DETAILS                 40004
#define ID_VIEW_SOFTSHADOWS             40005
#define ID_VIEW_BLOOM                   40006
#define ID_VIEW_SHADERLOD               40007
#define ID_SHADERLOD_DX9                40008
#define ID_SHADERLOD_DX8                40009
#define ID_SHADERLOD_FIXEDFUNCTION      40011
#define ID_VIEW_ANTIALIASING            40012
#define ID_VIEW_HEATDISTORTIONS         40013
#define ID_HEATDISTORTIONS_HEATDISTORTIONS 40014
#define ID_HEATDISTORTIONS_HEATDEBUG    40015
#define ID_VIEW_SETCAMERA               40016
#define ID_HELP_ABOUT                   40017
#define ID_SHADERLOD_DX8ATI             40018
#define ID_VIEW_HEATDEBUG               40019
#define ID_EDIT_SELECTALL               40035
#define ID_EDIT_DELETE                  40039
#define ID_VIEW_SHOWLOG                 40050
#define ID_VIEW_TOGGLELOG               40051
#define ID_VIEW_SHADERLOD40056          40056
#define ID_VIEW_DEBUGSHADOWS            40057
#define ID_FILE_HISTORY_0               50021
#define ID_EAW_UNMODDED                 60100
#define ID_EAW_FOC_UNMODDED             60200
#define ID_UAW_EA_BETA_UNMODDED         60300

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40057
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
