version: 1.2.{build}
install:
  git submodule update --init --recursive

build:
  verbosity: minimal

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

artifacts:
  - path: '**\AloViewer.exe'
    name: AloViewer
